/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    safelist: [
      { pattern: /text-+/ },
      { pattern: /bg-+/ },
      { pattern: /border-+/ },
      { pattern: /shadow-+/ },
      { pattern: /w-+/ },
      { pattern: /!bg-+/ },
    ],
    extend: {
      screens: {
        mobile480: "480px",
        tablet768: "768px",
        desktop1200: "1200px",
      },
      spacing: {
        xs4: "2px",
        xs3: "4px",
        xs2: "8px",
        xs: "12px",
        s: "16px",
        sPlus: "20px",
        m: "24px",
        m1: "28px",
        m2: "32px",
        m3: "38px",
        l: "40px",
        l2: "42px",
        xl: "48px",
        xl2: "56px",
        xl3: "64px",
        xl4: "72px",
      },
      boxShadow: {
        btFocus: "0 0 0 4px rgba(46, 144, 250, 1)",
      },
      borderRadius: {
        zero: "0px",
        minimal: "4px",
        medium: "8px",
        medium2: "12px",
        medium3: "20px",
        large: "24px",
        large2: "32px",
      },
      fontWeight: {
        400: "400",
        500: "500",
        600: "600",
      },
      colors: {
        // bg
        bgWhite: "#FFFFFF",
        bgContrast: "#1C1F23",
        bgGreyDark: "#2E3238",
        bgGreyLigth: "#F9F9F9",
        bgBrandDark: "#1570EF",
        bgBrandLight1: "#EFF8FF",
        bgBrandLight2: "#D1E9FF",
        bgBrandLight3: "#2E90FA",
        bgErrorDark: "#FEE4E2",
        bgErrorLight: "#FEF3F2",
        bgSuccessDark: "#D1FADF",
        bgSuccessLight: "#ECFDF3",
        bgWarningDark: "#FEF0C7",
        bgWarningLight: "#FFFAEB",
        bgPressedGrey: "#D1E9FF",
        bgPressedBlue: "#53B1FD",
        bgPressedDestructive: "#F97066",
        bgHover: "#FFFFFF",
        bgHoverGrey: "#FAFDFF",
        bgHoverBlue: "#1849A9",
        bgHoverDestructive: "#912018",
        bgDefaultBlue: "#1570EF",
        bgDefaultDestructive: "#D92D20",
        bgImg: "#F9F9F9",
        bgDisable: "#F9F9F9",

        // icon
        iconWhite: "#fff",
        iconPrimary: "#2E3238",
        iconSecondary: "#888D92",
        iconTertiary: "#E6E8EA",
        iconContrast: "#FFFFFF",
        iconBrand: "#1570EF",
        iconBrandDark: "#1849A9",
        iconError: "#F04438",
        iconSuccess: "#12B76A",
        iconWarning: "#F79009",
        iconDisabled: "#A7ABB0",

        // text
        textDisabled: "#A7ABB0",
        textBrand: "#1849A9",
        textTertiary: "#6B7075",
        textSecondary: "#41464C",
        textPrimary: "#1C1F23",
        textInputDefault: "#6B7075",
        textContrast: "#FFFFFF",
        textInputActive: "#1C1F23",
        textWarning: "#F79009",
        textError: "#D92D20",
        textSuccess: "#039855",

        // border
        borderDefault: "#C6CACD",
        borderDefault50: "#E6E8EA",
        borderHover: "#A7ABB0",
        borderDefaultBlue: "#1570EF",
        borderHoverBlue: "#1849A9",
        borderPressedBlue: "#53B1FD",
        borderActive: "#175CD3",
        borderError: "#F97066",
        borderSuccess: "#32D583",
        borderDisabled: "#E6E8EA",

        // static
        staticBlack: "#000000",
        staticWhite: "#FFFFFF",

        transparent: "transparent",
      },
    },
  },
  plugins: [],
};
